#!/bin/sh
. ~/.config/configs/hyprv.conf

#Check the version 
VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

#show a message
# notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to $MODESTR"

#set the measuring unit
if [[ $SET_MESU == "I" ]]; then
    ln -sf ~/.config/configs/waybar/conf/mesu-imp.jsonc ~/.config/configs/waybar/conf/mesu.jsonc
elif [[ $SET_MESU == "M" ]]; then
    ln -sf ~/.config/configs/waybar/conf/mesu-met.jsonc ~/.config/configs/waybar/conf/mesu.jsonc
fi

xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Adwaita-Dark"

xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-Dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-Dark"


#update the sddm image
# cp -f ~/.config/configs/backgrounds/$VER'-background'$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#reset mako
sleep 1
pkill mako
mako &

#restart the waybar
#killall -SIGUSR2 waybar <-- start causing web brwsers to close so switched to below...
pkill waybar
waybar &

if [[ $VER == "v4" ]]; then
    waybar --config ~/.config/configs/waybar/conf/v4-config-bottom.jsonc
fi