#!/bin/bash

# Function to get current volume using pamixer
get_volume() {
    pamixer --get-volume
}

# Function to get current icon based on volume and mute status
get_icon() {
    local volume=$(get_volume)
    local mute=$(pamixer --get-mute)
    
    if [ "$mute" = "true" ]; then
        echo ""  # Mute icon
    elif [ "$volume" -eq 0 ]; then
        echo ""  # Mute icon
    elif [ "$volume" -lt 33 ]; then
        echo ""  # Low volume icon
    elif [ "$volume" -lt 67 ]; then
        echo ""  # Medium volume icon
    else
        echo ""  # High volume icon
    fi
}

# Function to send notification
notify_user() {
    local volume=$(get_volume)
    local icon=$(get_icon)
    
    notify-send -h string:x-canonical-private-synchronous:sys-notify \
        -u low -i "$icon" "Volume: $volume%"
}

# Function to output volume status in JSON format for Waybar
output_waybar() {
    local volume=$(get_volume)
    local icon=$(get_icon)
    
    #local output="{\"text\": \"$icon $volume%\", \"class\": \"volume\"}"
	local output="{\"text\": \"$icon\", \"class\": \"volume\"}"
    echo "$output" >> /tmp/waybar-volume-debug.log  # Debugging output
    echo "$output"
}

# Increase Volume
inc_volume() {
    pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
    if [ "$(pamixer --get-mute)" == "false" ]; then
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify \
            -u low -i "" "Volume Switched OFF"
    elif [ "$(pamixer --get-mute)" == "true" ]; then
        pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify \
            -u low -i "$(get_icon)" "Volume Switched ON"
    fi
}

# Toggle Mic
toggle_mic() {
    if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
        pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify \
            -u low -i "" "Microphone Switched OFF"
    elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        pamixer --default-source -u && notify-send -h string:x-canonical-private-synchronous:sys-notify \
            -u low -i "" "Microphone Switched ON"
    fi
}

# Get mic icon
get_mic_icon() {
    current=$(pamixer --default-source --get-volume)
    if [[ "$current" -eq "0" ]]; then
        echo ""
    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        echo ""
    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        echo ""
    elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
        echo ""
    fi
}

# Notify mic user
notify_mic_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(pamixer --default-source --get-volume) %"
}

# Increase MIC Volume
inc_mic_volume() {
    pamixer --default-source -i 5 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
    pamixer --default-source -d 5 && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
    toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
    get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
    get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
    inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
    dec_mic_volume
else
    output_waybar
fi
